package com.neu.po;

public class ConstantItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.ID
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.ConstantTypeID
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    private ConstantType type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.ConstantCode
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.ConstantName
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constantitem.DelMark
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    private Integer delmark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.ID
     *
     * @return the value of constantitem.ID
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.ID
     *
     * @param id the value for constantitem.ID
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.ConstantTypeID
     *
     * @return the value of constantitem.ConstantTypeID
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public ConstantType getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.ConstantTypeID
     *
     * @param type the value for constantitem.ConstantTypeID
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public void setType(ConstantType type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.ConstantCode
     *
     * @return the value of constantitem.ConstantCode
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.ConstantCode
     *
     * @param code the value for constantitem.ConstantCode
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.ConstantName
     *
     * @return the value of constantitem.ConstantName
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.ConstantName
     *
     * @param name the value for constantitem.ConstantName
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constantitem.DelMark
     *
     * @return the value of constantitem.DelMark
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constantitem.DelMark
     *
     * @param delmark the value for constantitem.DelMark
     *
     * @mbg.generated Fri Oct 09 09:18:16 CST 2020
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }
}