package com.neu.po;

public class ConstantType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constanttype.ID
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constanttype.ConstantTypeCode
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    private String constanttypecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constanttype.ConstantTypeName
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    private String constanttypename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column constanttype.DelMark
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    private Integer delmark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constanttype.ID
     *
     * @return the value of constanttype.ID
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constanttype.ID
     *
     * @param id the value for constanttype.ID
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constanttype.ConstantTypeCode
     *
     * @return the value of constanttype.ConstantTypeCode
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public String getConstanttypecode() {
        return constanttypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constanttype.ConstantTypeCode
     *
     * @param constanttypecode the value for constanttype.ConstantTypeCode
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public void setConstanttypecode(String constanttypecode) {
        this.constanttypecode = constanttypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constanttype.ConstantTypeName
     *
     * @return the value of constanttype.ConstantTypeName
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public String getConstanttypename() {
        return constanttypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constanttype.ConstantTypeName
     *
     * @param constanttypename the value for constanttype.ConstantTypeName
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public void setConstanttypename(String constanttypename) {
        this.constanttypename = constanttypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column constanttype.DelMark
     *
     * @return the value of constanttype.DelMark
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column constanttype.DelMark
     *
     * @param delmark the value for constanttype.DelMark
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }
}