package com.neu.po;

import java.util.ArrayList;
import java.util.List;

public class ConstantTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public ConstantTypeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeIsNull() {
            addCriterion("ConstantTypeCode is null");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeIsNotNull() {
            addCriterion("ConstantTypeCode is not null");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeEqualTo(String value) {
            addCriterion("ConstantTypeCode =", value, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeNotEqualTo(String value) {
            addCriterion("ConstantTypeCode <>", value, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeGreaterThan(String value) {
            addCriterion("ConstantTypeCode >", value, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeGreaterThanOrEqualTo(String value) {
            addCriterion("ConstantTypeCode >=", value, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeLessThan(String value) {
            addCriterion("ConstantTypeCode <", value, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeLessThanOrEqualTo(String value) {
            addCriterion("ConstantTypeCode <=", value, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeLike(String value) {
            addCriterion("ConstantTypeCode like", value, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeNotLike(String value) {
            addCriterion("ConstantTypeCode not like", value, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeIn(List<String> values) {
            addCriterion("ConstantTypeCode in", values, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeNotIn(List<String> values) {
            addCriterion("ConstantTypeCode not in", values, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeBetween(String value1, String value2) {
            addCriterion("ConstantTypeCode between", value1, value2, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypecodeNotBetween(String value1, String value2) {
            addCriterion("ConstantTypeCode not between", value1, value2, "constanttypecode");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameIsNull() {
            addCriterion("ConstantTypeName is null");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameIsNotNull() {
            addCriterion("ConstantTypeName is not null");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameEqualTo(String value) {
            addCriterion("ConstantTypeName =", value, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameNotEqualTo(String value) {
            addCriterion("ConstantTypeName <>", value, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameGreaterThan(String value) {
            addCriterion("ConstantTypeName >", value, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameGreaterThanOrEqualTo(String value) {
            addCriterion("ConstantTypeName >=", value, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameLessThan(String value) {
            addCriterion("ConstantTypeName <", value, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameLessThanOrEqualTo(String value) {
            addCriterion("ConstantTypeName <=", value, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameLike(String value) {
            addCriterion("ConstantTypeName like", value, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameNotLike(String value) {
            addCriterion("ConstantTypeName not like", value, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameIn(List<String> values) {
            addCriterion("ConstantTypeName in", values, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameNotIn(List<String> values) {
            addCriterion("ConstantTypeName not in", values, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameBetween(String value1, String value2) {
            addCriterion("ConstantTypeName between", value1, value2, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andConstanttypenameNotBetween(String value1, String value2) {
            addCriterion("ConstantTypeName not between", value1, value2, "constanttypename");
            return (Criteria) this;
        }

        public Criteria andDelmarkIsNull() {
            addCriterion("DelMark is null");
            return (Criteria) this;
        }

        public Criteria andDelmarkIsNotNull() {
            addCriterion("DelMark is not null");
            return (Criteria) this;
        }

        public Criteria andDelmarkEqualTo(Integer value) {
            addCriterion("DelMark =", value, "delmark");
            return (Criteria) this;
        }

        public Criteria andDelmarkNotEqualTo(Integer value) {
            addCriterion("DelMark <>", value, "delmark");
            return (Criteria) this;
        }

        public Criteria andDelmarkGreaterThan(Integer value) {
            addCriterion("DelMark >", value, "delmark");
            return (Criteria) this;
        }

        public Criteria andDelmarkGreaterThanOrEqualTo(Integer value) {
            addCriterion("DelMark >=", value, "delmark");
            return (Criteria) this;
        }

        public Criteria andDelmarkLessThan(Integer value) {
            addCriterion("DelMark <", value, "delmark");
            return (Criteria) this;
        }

        public Criteria andDelmarkLessThanOrEqualTo(Integer value) {
            addCriterion("DelMark <=", value, "delmark");
            return (Criteria) this;
        }

        public Criteria andDelmarkIn(List<Integer> values) {
            addCriterion("DelMark in", values, "delmark");
            return (Criteria) this;
        }

        public Criteria andDelmarkNotIn(List<Integer> values) {
            addCriterion("DelMark not in", values, "delmark");
            return (Criteria) this;
        }

        public Criteria andDelmarkBetween(Integer value1, Integer value2) {
            addCriterion("DelMark between", value1, value2, "delmark");
            return (Criteria) this;
        }

        public Criteria andDelmarkNotBetween(Integer value1, Integer value2) {
            addCriterion("DelMark not between", value1, value2, "delmark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table constanttype
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 30 09:56:15 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table constanttype
     *
     * @mbg.generated Wed Sep 30 09:56:15 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}