package com.neu.po;

import java.math.BigDecimal;

public class RegistLevel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registlevel.ID
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registlevel.RegistCode
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private String registcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registlevel.RegistName
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private String registname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registlevel.SequenceNo
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private Integer sequenceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registlevel.RegistFee
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private BigDecimal registfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registlevel.RegistQuota
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private Integer registquota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column registlevel.DelMark
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private Integer delmark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.ID
     *
     * @return the value of registlevel.ID
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.ID
     *
     * @param id the value for registlevel.ID
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.RegistCode
     *
     * @return the value of registlevel.RegistCode
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public String getRegistcode() {
        return registcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.RegistCode
     *
     * @param registcode the value for registlevel.RegistCode
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setRegistcode(String registcode) {
        this.registcode = registcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.RegistName
     *
     * @return the value of registlevel.RegistName
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public String getRegistname() {
        return registname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.RegistName
     *
     * @param registname the value for registlevel.RegistName
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setRegistname(String registname) {
        this.registname = registname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.SequenceNo
     *
     * @return the value of registlevel.SequenceNo
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public Integer getSequenceno() {
        return sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.SequenceNo
     *
     * @param sequenceno the value for registlevel.SequenceNo
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setSequenceno(Integer sequenceno) {
        this.sequenceno = sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.RegistFee
     *
     * @return the value of registlevel.RegistFee
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public BigDecimal getRegistfee() {
        return registfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.RegistFee
     *
     * @param registfee the value for registlevel.RegistFee
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setRegistfee(BigDecimal registfee) {
        this.registfee = registfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.RegistQuota
     *
     * @return the value of registlevel.RegistQuota
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public Integer getRegistquota() {
        return registquota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.RegistQuota
     *
     * @param registquota the value for registlevel.RegistQuota
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setRegistquota(Integer registquota) {
        this.registquota = registquota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column registlevel.DelMark
     *
     * @return the value of registlevel.DelMark
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column registlevel.DelMark
     *
     * @param delmark the value for registlevel.DelMark
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }
}