package com.neu.po;

import java.util.Date;

public class Register {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.ID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.CaseNumber
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private String casenumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.RealName
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.Gender
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private ConstantItem ConstantItem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.IDnumber
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private String idnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.BirthDate
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.Age
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.AgeType
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private String agetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.HomeAddress
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private String homeaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.VisitDate
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private Date visitdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.Noon
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private String noon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.DeptID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private DepartMent DepartMent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.UserID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private User User1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.RegistLeID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private RegistLevel RegistLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.SettleID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private SettleCategory SettleCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.IsBook
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private String isbook;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.RegistTime
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private Date registtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.RegisterID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private User User2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register.VisitState
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    private Integer visitstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.ID
     *
     * @return the value of register.ID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.ID
     *
     * @param id the value for register.ID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.CaseNumber
     *
     * @return the value of register.CaseNumber
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public String getCasenumber() {
        return casenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.CaseNumber
     *
     * @param casenumber the value for register.CaseNumber
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setCasenumber(String casenumber) {
        this.casenumber = casenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.RealName
     *
     * @return the value of register.RealName
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.RealName
     *
     * @param realname the value for register.RealName
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.Gender
     *
     * @return the value of register.Gender
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public ConstantItem getConstantItem() {
        return ConstantItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.Gender
     *
     * @param ConstantItem the value for register.Gender
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setConstantItem(ConstantItem ConstantItem) {
        this.ConstantItem = ConstantItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.IDnumber
     *
     * @return the value of register.IDnumber
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.IDnumber
     *
     * @param idnumber the value for register.IDnumber
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.BirthDate
     *
     * @return the value of register.BirthDate
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.BirthDate
     *
     * @param birthdate the value for register.BirthDate
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.Age
     *
     * @return the value of register.Age
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.Age
     *
     * @param age the value for register.Age
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.AgeType
     *
     * @return the value of register.AgeType
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public String getAgetype() {
        return agetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.AgeType
     *
     * @param agetype the value for register.AgeType
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setAgetype(String agetype) {
        this.agetype = agetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.HomeAddress
     *
     * @return the value of register.HomeAddress
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public String getHomeaddress() {
        return homeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.HomeAddress
     *
     * @param homeaddress the value for register.HomeAddress
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setHomeaddress(String homeaddress) {
        this.homeaddress = homeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.VisitDate
     *
     * @return the value of register.VisitDate
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public Date getVisitdate() {
        return visitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.VisitDate
     *
     * @param visitdate the value for register.VisitDate
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setVisitdate(Date visitdate) {
        this.visitdate = visitdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.Noon
     *
     * @return the value of register.Noon
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public String getNoon() {
        return noon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.Noon
     *
     * @param noon the value for register.Noon
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setNoon(String noon) {
        this.noon = noon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.DeptID
     *
     * @return the value of register.DeptID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public DepartMent getDepartMent() {
        return DepartMent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.DeptID
     *
     * @param DepartMent the value for register.DeptID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setDepartMent(DepartMent DepartMent) {
        this.DepartMent = DepartMent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.UserID
     *
     * @return the value of register.UserID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public User getUser1() {
        return User1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.UserID
     *
     * @param User1 the value for register.UserID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setUser1(User User1) {
        this.User1 = User1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.RegistLeID
     *
     * @return the value of register.RegistLeID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public RegistLevel getRegistLevel() {
        return RegistLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.RegistLeID
     *
     * @param RegistLevel the value for register.RegistLeID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setRegistLevel(RegistLevel RegistLevel) {
        this.RegistLevel = RegistLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.SettleID
     *
     * @return the value of register.SettleID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public SettleCategory getSettleCategory() {
        return SettleCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.SettleID
     *
     * @param SettleCategory the value for register.SettleID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setSettleCategory(SettleCategory SettleCategory) {
        this.SettleCategory = SettleCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.IsBook
     *
     * @return the value of register.IsBook
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public String getIsbook() {
        return isbook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.IsBook
     *
     * @param isbook the value for register.IsBook
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setIsbook(String isbook) {
        this.isbook = isbook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.RegistTime
     *
     * @return the value of register.RegistTime
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public Date getRegisttime() {
        return registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.RegistTime
     *
     * @param registtime the value for register.RegistTime
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setRegisttime(Date registtime) {
        this.registtime = registtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.RegisterID
     *
     * @return the value of register.RegisterID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public User getUser2() {
        return User2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.RegisterID
     *
     * @param User2 the value for register.RegisterID
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setUser2(User User2) {
        this.User2 = User2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register.VisitState
     *
     * @return the value of register.VisitState
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public Integer getVisitstate() {
        return visitstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register.VisitState
     *
     * @param visitstate the value for register.VisitState
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setVisitstate(Integer visitstate) {
        this.visitstate = visitstate;
    }
}