package com.neu.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RegisterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public RegisterExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCasenumberIsNull() {
            addCriterion("CaseNumber is null");
            return (Criteria) this;
        }

        public Criteria andCasenumberIsNotNull() {
            addCriterion("CaseNumber is not null");
            return (Criteria) this;
        }

        public Criteria andCasenumberEqualTo(String value) {
            addCriterion("CaseNumber =", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotEqualTo(String value) {
            addCriterion("CaseNumber <>", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThan(String value) {
            addCriterion("CaseNumber >", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberGreaterThanOrEqualTo(String value) {
            addCriterion("CaseNumber >=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThan(String value) {
            addCriterion("CaseNumber <", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLessThanOrEqualTo(String value) {
            addCriterion("CaseNumber <=", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberLike(String value) {
            addCriterion("CaseNumber like", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotLike(String value) {
            addCriterion("CaseNumber not like", value, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberIn(List<String> values) {
            addCriterion("CaseNumber in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotIn(List<String> values) {
            addCriterion("CaseNumber not in", values, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberBetween(String value1, String value2) {
            addCriterion("CaseNumber between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andCasenumberNotBetween(String value1, String value2) {
            addCriterion("CaseNumber not between", value1, value2, "casenumber");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("RealName is null");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("RealName is not null");
            return (Criteria) this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("RealName =", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("RealName <>", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("RealName >", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("RealName >=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("RealName <", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("RealName <=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("RealName like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("RealName not like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameIn(List<String> values) {
            addCriterion("RealName in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotIn(List<String> values) {
            addCriterion("RealName not in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("RealName between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("RealName not between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andConstantItemIsNull() {
            addCriterion("Gender is null");
            return (Criteria) this;
        }

        public Criteria andConstantItemIsNotNull() {
            addCriterion("Gender is not null");
            return (Criteria) this;
        }

        public Criteria andConstantItemEqualTo(ConstantItem value) {
            addCriterion("Gender =", value, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andConstantItemNotEqualTo(ConstantItem value) {
            addCriterion("Gender <>", value, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andConstantItemGreaterThan(ConstantItem value) {
            addCriterion("Gender >", value, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andConstantItemGreaterThanOrEqualTo(ConstantItem value) {
            addCriterion("Gender >=", value, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andConstantItemLessThan(ConstantItem value) {
            addCriterion("Gender <", value, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andConstantItemLessThanOrEqualTo(ConstantItem value) {
            addCriterion("Gender <=", value, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andConstantItemIn(List<ConstantItem> values) {
            addCriterion("Gender in", values, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andConstantItemNotIn(List<ConstantItem> values) {
            addCriterion("Gender not in", values, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andConstantItemBetween(ConstantItem value1, ConstantItem value2) {
            addCriterion("Gender between", value1, value2, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andConstantItemNotBetween(ConstantItem value1, ConstantItem value2) {
            addCriterion("Gender not between", value1, value2, "ConstantItem");
            return (Criteria) this;
        }

        public Criteria andIdnumberIsNull() {
            addCriterion("IDnumber is null");
            return (Criteria) this;
        }

        public Criteria andIdnumberIsNotNull() {
            addCriterion("IDnumber is not null");
            return (Criteria) this;
        }

        public Criteria andIdnumberEqualTo(String value) {
            addCriterion("IDnumber =", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotEqualTo(String value) {
            addCriterion("IDnumber <>", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberGreaterThan(String value) {
            addCriterion("IDnumber >", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberGreaterThanOrEqualTo(String value) {
            addCriterion("IDnumber >=", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberLessThan(String value) {
            addCriterion("IDnumber <", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberLessThanOrEqualTo(String value) {
            addCriterion("IDnumber <=", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberLike(String value) {
            addCriterion("IDnumber like", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotLike(String value) {
            addCriterion("IDnumber not like", value, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberIn(List<String> values) {
            addCriterion("IDnumber in", values, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotIn(List<String> values) {
            addCriterion("IDnumber not in", values, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberBetween(String value1, String value2) {
            addCriterion("IDnumber between", value1, value2, "idnumber");
            return (Criteria) this;
        }

        public Criteria andIdnumberNotBetween(String value1, String value2) {
            addCriterion("IDnumber not between", value1, value2, "idnumber");
            return (Criteria) this;
        }

        public Criteria andBirthdateIsNull() {
            addCriterion("BirthDate is null");
            return (Criteria) this;
        }

        public Criteria andBirthdateIsNotNull() {
            addCriterion("BirthDate is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdateEqualTo(Date value) {
            addCriterionForJDBCDate("BirthDate =", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("BirthDate <>", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateGreaterThan(Date value) {
            addCriterionForJDBCDate("BirthDate >", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("BirthDate >=", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateLessThan(Date value) {
            addCriterionForJDBCDate("BirthDate <", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("BirthDate <=", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateIn(List<Date> values) {
            addCriterionForJDBCDate("BirthDate in", values, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("BirthDate not in", values, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("BirthDate between", value1, value2, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("BirthDate not between", value1, value2, "birthdate");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("Age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("Age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("Age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("Age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("Age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("Age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("Age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("Age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("Age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("Age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("Age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("Age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgetypeIsNull() {
            addCriterion("AgeType is null");
            return (Criteria) this;
        }

        public Criteria andAgetypeIsNotNull() {
            addCriterion("AgeType is not null");
            return (Criteria) this;
        }

        public Criteria andAgetypeEqualTo(String value) {
            addCriterion("AgeType =", value, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeNotEqualTo(String value) {
            addCriterion("AgeType <>", value, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeGreaterThan(String value) {
            addCriterion("AgeType >", value, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeGreaterThanOrEqualTo(String value) {
            addCriterion("AgeType >=", value, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeLessThan(String value) {
            addCriterion("AgeType <", value, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeLessThanOrEqualTo(String value) {
            addCriterion("AgeType <=", value, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeLike(String value) {
            addCriterion("AgeType like", value, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeNotLike(String value) {
            addCriterion("AgeType not like", value, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeIn(List<String> values) {
            addCriterion("AgeType in", values, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeNotIn(List<String> values) {
            addCriterion("AgeType not in", values, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeBetween(String value1, String value2) {
            addCriterion("AgeType between", value1, value2, "agetype");
            return (Criteria) this;
        }

        public Criteria andAgetypeNotBetween(String value1, String value2) {
            addCriterion("AgeType not between", value1, value2, "agetype");
            return (Criteria) this;
        }

        public Criteria andHomeaddressIsNull() {
            addCriterion("HomeAddress is null");
            return (Criteria) this;
        }

        public Criteria andHomeaddressIsNotNull() {
            addCriterion("HomeAddress is not null");
            return (Criteria) this;
        }

        public Criteria andHomeaddressEqualTo(String value) {
            addCriterion("HomeAddress =", value, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressNotEqualTo(String value) {
            addCriterion("HomeAddress <>", value, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressGreaterThan(String value) {
            addCriterion("HomeAddress >", value, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressGreaterThanOrEqualTo(String value) {
            addCriterion("HomeAddress >=", value, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressLessThan(String value) {
            addCriterion("HomeAddress <", value, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressLessThanOrEqualTo(String value) {
            addCriterion("HomeAddress <=", value, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressLike(String value) {
            addCriterion("HomeAddress like", value, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressNotLike(String value) {
            addCriterion("HomeAddress not like", value, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressIn(List<String> values) {
            addCriterion("HomeAddress in", values, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressNotIn(List<String> values) {
            addCriterion("HomeAddress not in", values, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressBetween(String value1, String value2) {
            addCriterion("HomeAddress between", value1, value2, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andHomeaddressNotBetween(String value1, String value2) {
            addCriterion("HomeAddress not between", value1, value2, "homeaddress");
            return (Criteria) this;
        }

        public Criteria andVisitdateIsNull() {
            addCriterion("VisitDate is null");
            return (Criteria) this;
        }

        public Criteria andVisitdateIsNotNull() {
            addCriterion("VisitDate is not null");
            return (Criteria) this;
        }

        public Criteria andVisitdateEqualTo(Date value) {
            addCriterionForJDBCDate("VisitDate =", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateNotEqualTo(Date value) {
            addCriterionForJDBCDate("VisitDate <>", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateGreaterThan(Date value) {
            addCriterionForJDBCDate("VisitDate >", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VisitDate >=", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateLessThan(Date value) {
            addCriterionForJDBCDate("VisitDate <", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("VisitDate <=", value, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateIn(List<Date> values) {
            addCriterionForJDBCDate("VisitDate in", values, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateNotIn(List<Date> values) {
            addCriterionForJDBCDate("VisitDate not in", values, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VisitDate between", value1, value2, "visitdate");
            return (Criteria) this;
        }

        public Criteria andVisitdateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("VisitDate not between", value1, value2, "visitdate");
            return (Criteria) this;
        }

        public Criteria andNoonIsNull() {
            addCriterion("Noon is null");
            return (Criteria) this;
        }

        public Criteria andNoonIsNotNull() {
            addCriterion("Noon is not null");
            return (Criteria) this;
        }

        public Criteria andNoonEqualTo(String value) {
            addCriterion("Noon =", value, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonNotEqualTo(String value) {
            addCriterion("Noon <>", value, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonGreaterThan(String value) {
            addCriterion("Noon >", value, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonGreaterThanOrEqualTo(String value) {
            addCriterion("Noon >=", value, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonLessThan(String value) {
            addCriterion("Noon <", value, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonLessThanOrEqualTo(String value) {
            addCriterion("Noon <=", value, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonLike(String value) {
            addCriterion("Noon like", value, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonNotLike(String value) {
            addCriterion("Noon not like", value, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonIn(List<String> values) {
            addCriterion("Noon in", values, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonNotIn(List<String> values) {
            addCriterion("Noon not in", values, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonBetween(String value1, String value2) {
            addCriterion("Noon between", value1, value2, "noon");
            return (Criteria) this;
        }

        public Criteria andNoonNotBetween(String value1, String value2) {
            addCriterion("Noon not between", value1, value2, "noon");
            return (Criteria) this;
        }

        public Criteria andDepartMentIsNull() {
            addCriterion("DeptID is null");
            return (Criteria) this;
        }

        public Criteria andDepartMentIsNotNull() {
            addCriterion("DeptID is not null");
            return (Criteria) this;
        }

        public Criteria andDepartMentEqualTo(DepartMent value) {
            addCriterion("DeptID =", value, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andDepartMentNotEqualTo(DepartMent value) {
            addCriterion("DeptID <>", value, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andDepartMentGreaterThan(DepartMent value) {
            addCriterion("DeptID >", value, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andDepartMentGreaterThanOrEqualTo(DepartMent value) {
            addCriterion("DeptID >=", value, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andDepartMentLessThan(DepartMent value) {
            addCriterion("DeptID <", value, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andDepartMentLessThanOrEqualTo(DepartMent value) {
            addCriterion("DeptID <=", value, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andDepartMentIn(List<DepartMent> values) {
            addCriterion("DeptID in", values, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andDepartMentNotIn(List<DepartMent> values) {
            addCriterion("DeptID not in", values, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andDepartMentBetween(DepartMent value1, DepartMent value2) {
            addCriterion("DeptID between", value1, value2, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andDepartMentNotBetween(DepartMent value1, DepartMent value2) {
            addCriterion("DeptID not between", value1, value2, "DepartMent");
            return (Criteria) this;
        }

        public Criteria andUser1IsNull() {
            addCriterion("UserID is null");
            return (Criteria) this;
        }

        public Criteria andUser1IsNotNull() {
            addCriterion("UserID is not null");
            return (Criteria) this;
        }

        public Criteria andUser1EqualTo(User value) {
            addCriterion("UserID =", value, "User1");
            return (Criteria) this;
        }

        public Criteria andUser1NotEqualTo(User value) {
            addCriterion("UserID <>", value, "User1");
            return (Criteria) this;
        }

        public Criteria andUser1GreaterThan(User value) {
            addCriterion("UserID >", value, "User1");
            return (Criteria) this;
        }

        public Criteria andUser1GreaterThanOrEqualTo(User value) {
            addCriterion("UserID >=", value, "User1");
            return (Criteria) this;
        }

        public Criteria andUser1LessThan(User value) {
            addCriterion("UserID <", value, "User1");
            return (Criteria) this;
        }

        public Criteria andUser1LessThanOrEqualTo(User value) {
            addCriterion("UserID <=", value, "User1");
            return (Criteria) this;
        }

        public Criteria andUser1In(List<User> values) {
            addCriterion("UserID in", values, "User1");
            return (Criteria) this;
        }

        public Criteria andUser1NotIn(List<User> values) {
            addCriterion("UserID not in", values, "User1");
            return (Criteria) this;
        }

        public Criteria andUser1Between(User value1, User value2) {
            addCriterion("UserID between", value1, value2, "User1");
            return (Criteria) this;
        }

        public Criteria andUser1NotBetween(User value1, User value2) {
            addCriterion("UserID not between", value1, value2, "User1");
            return (Criteria) this;
        }

        public Criteria andRegistLevelIsNull() {
            addCriterion("RegistLeID is null");
            return (Criteria) this;
        }

        public Criteria andRegistLevelIsNotNull() {
            addCriterion("RegistLeID is not null");
            return (Criteria) this;
        }

        public Criteria andRegistLevelEqualTo(RegistLevel value) {
            addCriterion("RegistLeID =", value, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelNotEqualTo(RegistLevel value) {
            addCriterion("RegistLeID <>", value, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelGreaterThan(RegistLevel value) {
            addCriterion("RegistLeID >", value, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelGreaterThanOrEqualTo(RegistLevel value) {
            addCriterion("RegistLeID >=", value, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelLessThan(RegistLevel value) {
            addCriterion("RegistLeID <", value, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelLessThanOrEqualTo(RegistLevel value) {
            addCriterion("RegistLeID <=", value, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelIn(List<RegistLevel> values) {
            addCriterion("RegistLeID in", values, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelNotIn(List<RegistLevel> values) {
            addCriterion("RegistLeID not in", values, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelBetween(RegistLevel value1, RegistLevel value2) {
            addCriterion("RegistLeID between", value1, value2, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andRegistLevelNotBetween(RegistLevel value1, RegistLevel value2) {
            addCriterion("RegistLeID not between", value1, value2, "RegistLevel");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryIsNull() {
            addCriterion("SettleID is null");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryIsNotNull() {
            addCriterion("SettleID is not null");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryEqualTo(SettleCategory value) {
            addCriterion("SettleID =", value, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryNotEqualTo(SettleCategory value) {
            addCriterion("SettleID <>", value, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryGreaterThan(SettleCategory value) {
            addCriterion("SettleID >", value, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryGreaterThanOrEqualTo(SettleCategory value) {
            addCriterion("SettleID >=", value, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryLessThan(SettleCategory value) {
            addCriterion("SettleID <", value, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryLessThanOrEqualTo(SettleCategory value) {
            addCriterion("SettleID <=", value, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryIn(List<SettleCategory> values) {
            addCriterion("SettleID in", values, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryNotIn(List<SettleCategory> values) {
            addCriterion("SettleID not in", values, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryBetween(SettleCategory value1, SettleCategory value2) {
            addCriterion("SettleID between", value1, value2, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andSettleCategoryNotBetween(SettleCategory value1, SettleCategory value2) {
            addCriterion("SettleID not between", value1, value2, "SettleCategory");
            return (Criteria) this;
        }

        public Criteria andIsbookIsNull() {
            addCriterion("IsBook is null");
            return (Criteria) this;
        }

        public Criteria andIsbookIsNotNull() {
            addCriterion("IsBook is not null");
            return (Criteria) this;
        }

        public Criteria andIsbookEqualTo(String value) {
            addCriterion("IsBook =", value, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookNotEqualTo(String value) {
            addCriterion("IsBook <>", value, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookGreaterThan(String value) {
            addCriterion("IsBook >", value, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookGreaterThanOrEqualTo(String value) {
            addCriterion("IsBook >=", value, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookLessThan(String value) {
            addCriterion("IsBook <", value, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookLessThanOrEqualTo(String value) {
            addCriterion("IsBook <=", value, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookLike(String value) {
            addCriterion("IsBook like", value, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookNotLike(String value) {
            addCriterion("IsBook not like", value, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookIn(List<String> values) {
            addCriterion("IsBook in", values, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookNotIn(List<String> values) {
            addCriterion("IsBook not in", values, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookBetween(String value1, String value2) {
            addCriterion("IsBook between", value1, value2, "isbook");
            return (Criteria) this;
        }

        public Criteria andIsbookNotBetween(String value1, String value2) {
            addCriterion("IsBook not between", value1, value2, "isbook");
            return (Criteria) this;
        }

        public Criteria andRegisttimeIsNull() {
            addCriterion("RegistTime is null");
            return (Criteria) this;
        }

        public Criteria andRegisttimeIsNotNull() {
            addCriterion("RegistTime is not null");
            return (Criteria) this;
        }

        public Criteria andRegisttimeEqualTo(Date value) {
            addCriterion("RegistTime =", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotEqualTo(Date value) {
            addCriterion("RegistTime <>", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeGreaterThan(Date value) {
            addCriterion("RegistTime >", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("RegistTime >=", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeLessThan(Date value) {
            addCriterion("RegistTime <", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeLessThanOrEqualTo(Date value) {
            addCriterion("RegistTime <=", value, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeIn(List<Date> values) {
            addCriterion("RegistTime in", values, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotIn(List<Date> values) {
            addCriterion("RegistTime not in", values, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeBetween(Date value1, Date value2) {
            addCriterion("RegistTime between", value1, value2, "registtime");
            return (Criteria) this;
        }

        public Criteria andRegisttimeNotBetween(Date value1, Date value2) {
            addCriterion("RegistTime not between", value1, value2, "registtime");
            return (Criteria) this;
        }

        public Criteria andUser2IsNull() {
            addCriterion("RegisterID is null");
            return (Criteria) this;
        }

        public Criteria andUser2IsNotNull() {
            addCriterion("RegisterID is not null");
            return (Criteria) this;
        }

        public Criteria andUser2EqualTo(User value) {
            addCriterion("RegisterID =", value, "User2");
            return (Criteria) this;
        }

        public Criteria andUser2NotEqualTo(User value) {
            addCriterion("RegisterID <>", value, "User2");
            return (Criteria) this;
        }

        public Criteria andUser2GreaterThan(User value) {
            addCriterion("RegisterID >", value, "User2");
            return (Criteria) this;
        }

        public Criteria andUser2GreaterThanOrEqualTo(User value) {
            addCriterion("RegisterID >=", value, "User2");
            return (Criteria) this;
        }

        public Criteria andUser2LessThan(User value) {
            addCriterion("RegisterID <", value, "User2");
            return (Criteria) this;
        }

        public Criteria andUser2LessThanOrEqualTo(User value) {
            addCriterion("RegisterID <=", value, "User2");
            return (Criteria) this;
        }

        public Criteria andUser2In(List<User> values) {
            addCriterion("RegisterID in", values, "User2");
            return (Criteria) this;
        }

        public Criteria andUser2NotIn(List<User> values) {
            addCriterion("RegisterID not in", values, "User2");
            return (Criteria) this;
        }

        public Criteria andUser2Between(User value1, User value2) {
            addCriterion("RegisterID between", value1, value2, "User2");
            return (Criteria) this;
        }

        public Criteria andUser2NotBetween(User value1, User value2) {
            addCriterion("RegisterID not between", value1, value2, "User2");
            return (Criteria) this;
        }

        public Criteria andVisitstateIsNull() {
            addCriterion("VisitState is null");
            return (Criteria) this;
        }

        public Criteria andVisitstateIsNotNull() {
            addCriterion("VisitState is not null");
            return (Criteria) this;
        }

        public Criteria andVisitstateEqualTo(Integer value) {
            addCriterion("VisitState =", value, "visitstate");
            return (Criteria) this;
        }

        public Criteria andVisitstateNotEqualTo(Integer value) {
            addCriterion("VisitState <>", value, "visitstate");
            return (Criteria) this;
        }

        public Criteria andVisitstateGreaterThan(Integer value) {
            addCriterion("VisitState >", value, "visitstate");
            return (Criteria) this;
        }

        public Criteria andVisitstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("VisitState >=", value, "visitstate");
            return (Criteria) this;
        }

        public Criteria andVisitstateLessThan(Integer value) {
            addCriterion("VisitState <", value, "visitstate");
            return (Criteria) this;
        }

        public Criteria andVisitstateLessThanOrEqualTo(Integer value) {
            addCriterion("VisitState <=", value, "visitstate");
            return (Criteria) this;
        }

        public Criteria andVisitstateIn(List<Integer> values) {
            addCriterion("VisitState in", values, "visitstate");
            return (Criteria) this;
        }

        public Criteria andVisitstateNotIn(List<Integer> values) {
            addCriterion("VisitState not in", values, "visitstate");
            return (Criteria) this;
        }

        public Criteria andVisitstateBetween(Integer value1, Integer value2) {
            addCriterion("VisitState between", value1, value2, "visitstate");
            return (Criteria) this;
        }

        public Criteria andVisitstateNotBetween(Integer value1, Integer value2) {
            addCriterion("VisitState not between", value1, value2, "visitstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table register
     *
     * @mbg.generated do_not_delete_during_merge Thu Oct 15 10:55:42 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}