package com.neu.po;

public class SettleCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.ID
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.SettleCode
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private String settlecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.SettleName
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private String settlename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.SequenceNo
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private Integer sequenceno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settlecategory.DelMark
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    private Integer delmark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.ID
     *
     * @return the value of settlecategory.ID
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.ID
     *
     * @param id the value for settlecategory.ID
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.SettleCode
     *
     * @return the value of settlecategory.SettleCode
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public String getSettlecode() {
        return settlecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.SettleCode
     *
     * @param settlecode the value for settlecategory.SettleCode
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setSettlecode(String settlecode) {
        this.settlecode = settlecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.SettleName
     *
     * @return the value of settlecategory.SettleName
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public String getSettlename() {
        return settlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.SettleName
     *
     * @param settlename the value for settlecategory.SettleName
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setSettlename(String settlename) {
        this.settlename = settlename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.SequenceNo
     *
     * @return the value of settlecategory.SequenceNo
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public Integer getSequenceno() {
        return sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.SequenceNo
     *
     * @param sequenceno the value for settlecategory.SequenceNo
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setSequenceno(Integer sequenceno) {
        this.sequenceno = sequenceno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settlecategory.DelMark
     *
     * @return the value of settlecategory.DelMark
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settlecategory.DelMark
     *
     * @param delmark the value for settlecategory.DelMark
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }
}