package com.neu.mapper;

import com.neu.po.RegistLevel;
import com.neu.po.RegistLevelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegistLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    long countByExample(RegistLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    int deleteByExample(RegistLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    int insert(RegistLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    int insertSelective(RegistLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    List<RegistLevel> selectByExample(RegistLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    RegistLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") RegistLevel record, @Param("example") RegistLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    int updateByExample(@Param("record") RegistLevel record, @Param("example") RegistLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    int updateByPrimaryKeySelective(RegistLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registlevel
     *
     * @mbg.generated Thu Oct 15 10:35:53 CST 2020
     */
    int updateByPrimaryKey(RegistLevel record);
    
    List<RegistLevel> getAll();
}