package com.neu.mapper;

import com.neu.po.Register;
import com.neu.po.RegisterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegisterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    long countByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    int deleteByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    int insert(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    int insertSelective(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    List<Register> selectByExample(RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    Register selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Register record, @Param("example") RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    int updateByExample(@Param("record") Register record, @Param("example") RegisterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    int updateByPrimaryKeySelective(Register record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register
     *
     * @mbg.generated Thu Oct 15 10:55:42 CST 2020
     */
    int updateByPrimaryKey(Register record);
}