package com.neu.mapper;

import com.neu.po.Scheduling;
import com.neu.po.SchedulingExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchedulingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    long countByExample(SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    int deleteByExample(SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    int insert(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    int insertSelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    List<Scheduling> selectByExample(SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    Scheduling selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Scheduling record, @Param("example") SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    int updateByExample(@Param("record") Scheduling record, @Param("example") SchedulingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    int updateByPrimaryKeySelective(Scheduling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduling
     *
     * @mbg.generated Thu Oct 15 14:11:44 CST 2020
     */
    int updateByPrimaryKey(Scheduling record);
    
    List<Scheduling> getByDate(Date date);
    
    List<Scheduling> getByDateAndNoon(Date date,String noon);
    
    List<Scheduling> getByDateAndNoonAndDeptId(Date date, String noon, int deptId);
    
    List<Scheduling> getByDateAndNoonAndDeptIdAndRelId(Date date, String noon, int deptId, int relId);
}